FUN main
    // 1. Выводим приглашение
    CONST "Please enter your name: "
    NATIVE "print" 1

    // 2. Получаем динамические данные из C++
    // У функции 0 аргументов. Она положит результат (строку) на вершину стека
    NATIVE "read" 0

    // 3. Сохраняем полученную строку в локальную переменную
    SET player_name

    // 4. Формируем строку приветствия (используя конкатенацию ADD)
    CONST "Welcome to the game, "
    GET player_name
    ADD                       // Складываем две строки! На стеке "Welcome to the game,[ИМЯ]"

    CONST "!"
    ADD                       // Добавляем восклицательный знак

    // 5. Выводим итоговый результат
    NATIVE "print" 1

    RETURN