#include "TestUtils.hpp"

#include "../../IgniCLI/include/IgniCLI/Compiler.hpp"

#include <Core/LibraryLoader.hpp>
#include <RVM/Assembler.hpp>
#include <RVM/EventLoop.hpp>
#include <RVM/VirtualMachine.hpp>

#include <fstream>
#include <sstream>

namespace fs = std::filesystem;
using IgniPluginInitFn = void (*)(re::rvm::VirtualMachine*);

class E2ETestFixture : public ::testing::TestWithParam<fs::path>
{
protected:
	std::unique_ptr<re::LibraryLoader> m_stdlibPlugin;

	void SetUp() override
	{
		try
		{
			m_stdlibPlugin = std::make_unique<re::LibraryLoader>("IgniStdLib.dll");
		}
		catch (...)
		{
		}
	}
};

TEST_P(E2ETestFixture, ExecutesCorrectly)
{
	fs::path scriptPath = GetParam();
	std::string expectedOutput = ExtractExpectedOutput(scriptPath);

	std::vector<std::string> sourceFiles;

	if (fs::exists("assets/source/stdlib.igni"))
	{
		sourceFiles.push_back("assets/source/stdlib.igni");
	}
	sourceFiles.push_back(scriptPath.string());

	igni::Compiler compiler("assets/igni_grammar.txt");
	std::string asmCode;
	ASSERT_NO_THROW({
		asmCode = compiler.CompileFiles(sourceFiles);
	}) << "Compiler pipeline crashed on: "
	   << scriptPath.filename().string();

	ASSERT_FALSE(asmCode.empty()) << "Compiler returned empty assembly (Compilation Failed)";

	re::rvm::Assembler assembler;
	re::rvm::Chunk chunk;
	ASSERT_TRUE(assembler.Compile(asmCode, chunk)) << "Assembler failed to compile generated bytecode";

	re::rvm::EventLoop eventLoop;
	re::rvm::VirtualMachine vm;
	vm.SetDelayHandler([&eventLoop](const re::rvm::CoroutinePtr& coro, const std::uint64_t ms) {
		eventLoop.Delay(coro, ms);
	});

	if (m_stdlibPlugin)
	{
		m_stdlibPlugin->GetSymbol<IgniPluginInitFn>("IgniPluginInit")(&vm);
	}

	std::stringstream capturedOutput;
	std::streambuf* oldCout = std::cout.rdbuf(capturedOutput.rdbuf());

	auto result = vm.Interpret(chunk);
	if (result == re::rvm::InterpreterResult::Suspended)
	{
		result = eventLoop.Run(vm);
	}

	std::cout.rdbuf(oldCout);

	ASSERT_EQ(result, re::rvm::InterpreterResult::Success) << "Virtual Machine crashed or returned an error";

	EXPECT_EQ(capturedOutput.str(), expectedOutput) << "Output mismatch in script: " << scriptPath.filename().string();
}

INSTANTIATE_TEST_SUITE_P(
	IgniScripts,
	E2ETestFixture,
	::testing::ValuesIn(GetTestScripts()),
	[](const ::testing::TestParamInfo<fs::path>& info) {
		std::string name = info.param.stem().string();
		std::replace_if(name.begin(), name.end(), [](char c) { return !std::isalnum(c); }, '_');
		return name;
	});
